// <auto-generated />
namespace Village_project_teast_19._1._21.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addTableCitizen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTableCitizen));
        
        string IMigrationMetadata.Id
        {
            get { return "202201190936450_addTableCitizen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
